version: '3.4'
services:
  web:
    build: ./app
    env_file:
      - env_file
    networks:
      my-network:
        aliases:
        - flask-app

  db:
    image: postgres:latest

    container_name: postgres
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    env_file:
      - env_file
    networks:
      - my-network

  proxy:
    build: ./nginx
    container_name: nginx
    depends_on:
        - web
    volumes:
        - ./nginx/:/etc/nginx/conf.d/
    networks:
        - my-network
    ports:
        - 80:80

networks:
    my-network:
