
FROM python:3.7.3-alpine3.9

RUN mkdir -p /app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN pip install -r requirements.txt

COPY . /app/
ENV FLASK_APP=server.py

CMD flask run -h 0.0.0.0 -p 5000
