
FROM python:3.7.3-alpine3.9

RUN mkdir -p /app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN pip install -r requirements.txt

COPY . /app/
ENV FLASK_APP=server.py


